[package]
name = "tictac_toe"
version = "0.1.0"
authors = ["tif24048 <tif24048@tiffincityschools.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"